name: Deployment pipeline
on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
    types: [opened, synchronize]
jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: "24"
      - uses: superfly/flyctl-actions/setup-flyctl@master
        with:
          version: 0.4.52
      - name: Install dependencies
        run: npm install
      - name: Check style
        run: npm run eslint
      - name: Run npm test
        run: npm run test
      - name: Run npm build
        run: npm run build
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Run Playwright tests
        run: npm run test:e2e
      - name: Run flyctl deploy --remote-only
        if: ${{ github.event_name == 'push' && !contains(join(toJson(github.event.commits.*.message)),'#skip')}} 
        run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
  tag_release:
    needs: [simple_deployment_pipeline]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@4ed44965e0db8dab2b466a16da04aec3cc312fd8
        if: ${{ github.event_name == 'push' && !contains(join(toJson(github.event.commits.*.message)),'#skip')}}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch
  notify_build_failure:
    needs: [simple_deployment_pipeline]
    runs-on: ubuntu-latest
    steps:
    - name: Actions Status Discord
      uses: sarisia/actions-status-discord@v1.16.0
      if: ${{ failure() }}
      with:
        webhook: ${{ secrets.DISCORD_WEBHOOK }}
        status: ${{ job.status }}
        content: "❌ **Build Failed!** The pipeline encountered an error"
        title: "**Failure Details**"
        description: |
          **Repository:** `${{ github.event.repository.full_name}}`
          **Branch:** `${{ github.ref_name}}`
          **Commit:** `${{ github.sha}}`
          **Message:** `${{ github.event.head_commit.message }}`
          **Author:** `${{ github.event.head_commit.author }}`
          **Workflow:** `${{ github.workflow }}`
          **Job:** `${{ github.job }}`
  notify_deployment_success:
    needs: [tag_release]
    runs-on: ubuntu-latest
    steps:
    - name: Actions Status Discord
      uses: sarisia/actions-status-discord@v1.16.0
      if: ${{ success() }}
      with:
        webhook: ${{ secrets.DISCORD_WEBHOOK }}
        status: ${{ job.status }}
        content: "✅ **Deployment successful!** A new version deployed to production"
        title: "[**Deployment Details**](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})"
        description: |
          **Commit:** `${{ github.sha}}`
          **Message:** `${{ github.event.head_commit.message }}`
          **Author:** `${{ github.event.head_commit.author }}`
